apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: market-dojo-lite
  annotations:
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: market-dojo-sa
      containers:
      - image: REGISTRY_URL/market-dojo-lite:latest
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: '2'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 512Mi
        env:
        - name: RAILS_ENV
          value: 'production'
        - name: RAILS_SERVE_STATIC_FILES
          value: 'true'
        - name: RAILS_LOG_TO_STDOUT
          value: 'true'
        - name: PORT
          value: '8080'
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: rails-secret
              key: latest
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
        startupProbe:
          httpGet:
            path: /up
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 240
          timeoutSeconds: 240
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /up
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true