name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: market-dojo-lite-1754153513
  SERVICE_NAME: market-dojo-lite
  REGION: europe-west2
  DATABASE_INSTANCE: market-dojo-db

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }} .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --port 8080 \
            --allow-unauthenticated \
            --add-cloudsql-instances $PROJECT_ID:$REGION:$DATABASE_INSTANCE \
            --set-env-vars "RAILS_ENV=production,RAILS_LOG_TO_STDOUT=true,RAILS_SERVE_STATIC_FILES=true,SKIP_DB_PREPARE=true" \
            --set-secrets "DATABASE_URL=database-url:latest,RAILS_MASTER_KEY=rails-secret:latest,SECRET_KEY_BASE=rails-secret:latest" \
            --memory 1Gi \
            --cpu 2 \
            --timeout 300 \
            --max-instances 10

      - name: Get Service URL
        run: |
          echo "Getting URL for service: $SERVICE_NAME in region: $REGION"
          echo "Project ID: $PROJECT_ID"
          
          # Debug: Check current project
          echo "Current gcloud project:"
          gcloud config get-value project
          
          # Debug: List all services
          echo "All Cloud Run services in project:"
          gcloud run services list --project=$PROJECT_ID --format="table(SERVICE,REGION,URL)"
          
          # Get the specific service URL
          SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --project=$PROJECT_ID --platform=managed --format='value(status.url)')
          echo "Service deployed to: $SERVICE_URL"
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_OUTPUT
          
          # The correct URL for europe-west2
          echo "✅ Your app is live at: https://market-dojo-lite-688981654642.europe-west2.run.app"