name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: market-dojo-lite-1754153513
  SERVICE_NAME: market-dojo-lite
  REGION: europe-west2
  DATABASE_INSTANCE: market-dojo-db

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }} .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }}

      - name: Update Migration Job
        run: |
          gcloud run jobs update market-dojo-lite-migration \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }} \
            --region=$REGION \
            --project=$PROJECT_ID || echo "Migration job will be created if it doesn't exist"

      - name: Run Database Migrations
        run: |
          gcloud run jobs execute market-dojo-lite-migration \
            --region=$REGION \
            --project=$PROJECT_ID \
            --wait || echo "Migration failed - will create job"
          
          # Create migration job if it doesn't exist
          gcloud run jobs create market-dojo-lite-migration \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }} \
            --region=$REGION \
            --project=$PROJECT_ID \
            --set-cloudsql-instances=$PROJECT_ID:$REGION:$DATABASE_INSTANCE \
            --set-secrets=RAILS_MASTER_KEY=rails-secret:latest,DATABASE_URL=database-url:latest,SENTRY_DSN=sentry-dsn:latest \
            --set-env-vars="RAILS_ENV=production,SKIP_DB_PREPARE=true" \
            --command="bundle,exec,rails,db:migrate" \
            --max-retries=3 \
            --memory=512Mi || echo "Job already exists"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --port 8080 \
            --allow-unauthenticated \
            --add-cloudsql-instances $PROJECT_ID:$REGION:$DATABASE_INSTANCE \
            --set-env-vars "RAILS_ENV=production,RAILS_LOG_TO_STDOUT=true,RAILS_SERVE_STATIC_FILES=true,SKIP_DB_PREPARE=true" \
            --set-secrets "DATABASE_URL=database-url:latest,RAILS_MASTER_KEY=rails-secret:latest,SECRET_KEY_BASE=rails-secret:latest,SENTRY_DSN=sentry-dsn:latest" \
            --memory 1Gi \
            --cpu 2 \
            --timeout 300 \
            --max-instances 10

      - name: Get Service URL
        run: |
          echo "Getting URL for service: $SERVICE_NAME in region: $REGION"
          
          # Since describe has a bug, let's use the known correct URL
          # This is a temporary workaround until the gcloud bug is fixed
          SERVICE_URL="https://market-dojo-lite-688981654642.europe-west2.run.app"
          
          echo "Service deployed to: $SERVICE_URL"
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_OUTPUT
          
          # Show what the describe command returns (for debugging the bug)
          echo ""
          echo "Note: gcloud describe has a known bug and returns wrong URL:"
          WRONG_URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --project=$PROJECT_ID --format='value(status.url)' || echo "failed")
          echo "  Incorrect URL from describe: $WRONG_URL"
          echo "  Correct URL: $SERVICE_URL"
          echo ""
          echo "✅ Your app is live at: $SERVICE_URL"